name: Publish app

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_apps:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install six
        run: pip install six

      - name: Install NativeScript
        run: |
          yarn global add nativescript@latest
          tns doctor
          tns package-manager set yarn

      - name: Yarn dependencies
        run: yarn

      - name: tns prepare ios
        run: tns prepare ios --bundle --release --clean --env.production

      - name: fastlane ios beta
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          SIGNING_IDENTITY: ${{ secrets.SIGNING_IDENTITY }}
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'ios beta'
          skip-tracking: true

      - name: Create android keystore
        run: |
          mkdir fastlane/keys
          echo "${{ secrets.KEYSTORE_FILE_B64 }}" | base64 -D > fastlane/keys/mobile.keystore

      - name: fastlane android alpha
        env:
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          PLAYSTORE_JSON_KEY_DATA: ${{ secrets.PLAYSTORE_JSON_KEY_DATA }}
          LANG: en_GB.UTF-8
          LC_ALL: en_GB.UTF-8
        uses: maierj/fastlane-action@v1.2.0
        with:
          lane: 'android beta'
          skip-tracking: true
